version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: todo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # NestJS Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: always
    depends_on:
      - postgres
    environment:
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 12345678
      DB_DB: todo
      DB_SYNC: 'true'
      RUN_MIGRATIONS: 'true'
      DB_LOG: 'true'
      # Utils
      PORT: 8000
      MODE: DEV
      JWT_EXPIRES_IN: '60d'
      JWT_SECRET: secret
    ports:
      - "8000:8000"
    networks:
      - app_network

  # React Frontend 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: